apiVersion: v1
kind: Service
metadata:
  name: backend-relationship
spec:
  selector:
    app: relationship-pod
    tier: backend-relationship
  ports:
  - protocol: TCP
    port: 6004
    targetPort: 6004
  type: LoadBalancer