apiVersion: v1
kind: Service
metadata:
  name: backend-repa
spec:
  selector:
    app: repa-pod
    tier: backend-repa
  ports:
  - protocol: TCP
    port: 6003
    targetPort: 6003
  type: LoadBalancer