apiVersion: v1
kind: Service
metadata:
  name: backend-chats
spec:
  selector:
    app: chats-pod
    tier: backend-chats
  ports:
  - protocol: TCP
    port: 6006
    targetPort: 6006
  type: LoadBalancer