apiVersion: v1
kind: Service
metadata:
  name: backend-basket
spec:
  selector:
    app: basket-pod
    tier: backend-basket
  ports:
  - protocol: TCP
    port: 6007
    targetPort: 6007
  type: LoadBalancer